# fly.toml app configuration file generated for mememaker on 2023-07-04T18:02:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mememaker"
primary_region = "yyz"
kill_signal = "SIGINT"
kill_timeout = "5s"
